CREATE TABLE CLIENT_SESSION (
    SESSION_ID TEXT PRIMARY KEY,
    ACCESS_TOKEN TEXT,
    REFRESH_TOKEN TEXT,
    ID_TOKEN TEXT,
    USER_ID TEXT,
    LAST_ACCESS_TIME INTEGER,
    IV TEXT
);

CREATE TABLE SERVER_SESSION (
    ACCESS_TOKEN TEXT,
    IV TEXT
);