export const POLICIES = "policies";
export const SUCCESS = "Success";
export const INSURED_REVENUE = "insured_revenue";
export const DATA_COMPLIANCE = "data_compliance";
export const INSURANCE_HISTORY = "insurance_history";
export const QUOTES = "quotes";
export const INFO_SECURITY_MEASURES = "info_security_measures";
export const OPTIONAL_EXTENSIONS = "optional_extensions";
export const SEARCHQUERY_INPUT_THROTTLE_TIMEOUT = 2000;
export const QUOTED = "quoted";
export const PENDING_REFERRAL = "pending referral";
export const DECLINED = "declined";
export const BIND = "bind";
export const POLICY = "policy";
export const BOUND = "bound";
export const RENEW = "renew";
export const REFER = "refer";
export const CANCEL = "cancel";
export const REFERRED = "referred";
export const REJECT = "reject";
export const HUMAN_RESOURCES_SECURITY = "HUMAN RESOURCES SECURITY";
export const ACCESS_CONTROL = "ACCESS CONTROL";
export const CLOSED_LOST = "closed lost";
export const ENDORSE = "endorse";
export const PRE_QUOTE = "pre-quote";
export const DASHBOARD = "dashboard";
export const INSURED_DOMAIN_BLACKLISTED = "insured-domain-blacklisted";
export const CONFIRM_TERM_FOR_REVENUE_DETAILS =
	"I confirm that my client (policy holder) is/will be a CGT small business entity (within the meaning of section 152-10 (1AA) of the Income Tax Assessment Act 1997 of the Commonwealth) for the income year in which the insurance is effected or renewed and that I have obtained a declaration to that effect from my client which I am able to produce if requested to do so by the Chief Commissioner.";
export const API_PARAMS = "apexrest/sfapi/v1/";
export const CYBER = "cyber";
export const DOMAINCHECK = "domaincheck";
export const LOSS_HISTORY = "loss_history";
export const OPERATION_SECURITY = "operation_security";
export const COMMISSION = "commissions";
export const COVERAGES = "coverages";
export const EDIT_QUOTE_OPTIONS = "quoteoptions";
export const SOCIAL_ENGG_FRAUD = "social_engineering_fraud";
export const REVENUE_DETAILS = "revenue_details";
export const GENERAL_ENQUIRY = "general-enquiry";
export const POLICY_WORDING_DOCUMENT_NAME =
	"ami cyber insurance policy wording.pdf";
export const RESTART = "restart";
export const NZD = "NZD";
export const BI_TIME_ACCESS_TOOLTIP =
	"There is no dollar excess payable for Business Interruption Claims. We will cover losses incurred 12 hours after a Cyber Event that directly causes Business Interruption Loss, subject to terms and conditions.";
export const ACTIVE_POLICY_OR_QUOTE = "activepolicyorquote";
export const BINDNZ = "bind";
export const INSURED_DOMAIN_EMPTY = "insured-domain-empty";
export const EMAIL_DOCUMENTS = "emaildocuments";
export const PURCHASE = "purchase";
export const ENGLISH = "en";
export const COMPLETE = "complete";
export const I_DO_NOT_COLLECT_ANY_INFORMATION =
	"i do not collect any information";
export const NEW = "new";
export const CLOSED_WON = "closed won";
export const RENEWAL = "renewal";
export const USER_CREATION_FAILED = "USER_CREATION_FAILED";
export const USER_CREATED_SUCCESSFULLY = "USER_CREATED_SUCCESSFULLY";
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
export const EMAIL_VERIFICATION_CODE_SENT = "EMAIL_VERIFICATION_CODE_SENT";
export const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST";
export const ACCOUNT_CREATION_FAILED_FOR_THIS_EMAIL =
	"account creation failed for this email";
export const ACCOUNT_ALREADY_EXISTS =
	"user with specified email address already exists";
export const MAX_RETRY = 3;
export const SF_UUID = "custom:sf_uuid";
export const AUTHENTICATION_SUCCESSFUL = "AUTHENTICATION_SUCCESSFUL";
export const RESEND_OTP_SUCCESSFUL = "RESEND_OTP_SUCCESSFUL";
export const INVALID_OTP = "INVALID_OTP";
export const AUTHENTICATION_FAILED="AUTHENTICATION_FAILED"
export const RESEND_OTP_SENT="OTP sent successfully."
export const PHONE_OTP_SENT="PHONE_OTP_SENT"
export const PHONE_OTP_GENERATION_FAILED="PHONE_OTP_GENERATION_FAILED"
export const PHONE_OTP_VERIFICATION_FAILED="PHONE_OTP_VERIFICATION_FAILED"
export const PHONE_OTP_VERIFICATION_SUCCESSFUL="PHONE_OTP_VERIFICATION_SUCCESSFUL"
export const PHONE_UPDATED="PHONE_UPDATED"
export const PHONE_UPDATION_FAILED="PHONE_UPDATION_FAILED"
export const INVALID_PHONE_OTP="INVALID_PHONE_OTP"
export const OTP_LIMIT_REACHED="OTP_LIMIT_REACHED"
export const TOO_MANY_REQUESTS="TOO_MANY_REQUESTS"
export const OTP_EXPIRED="OTP_EXPIRED"
export const ENDORSEMENT = "endorsement";
export const CANCELLATION = "cancellation";
export const CANCELLED = "cancelled";
export const COI = "coc"
export const WINDCAVE_NOTIFICATION_CALLBACK = "windcavenotifcallback"
export const QUOTE_OPTION_ID = "quote_option_id"
export const STORE_WINDCAVE_SESSION = "storewindcavesession"
export const VALIDATE_PROMO_CODE = "validatepromocode"
export const BUSINESS_DETAILS = "business_details";
